replicaCount: 1

app:
  env: prod

image:
  repository: gcr.io/heptio-images/ks-guestbook-demo
  pullPolicy: IfNotPresent
  tag: "0.2"

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 2
    memory: 2Gi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
