apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://34.48.20.151
      - cluster: prod
        url: https://35.188.199.89
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        path: guest-book
        repoURL: https://github.com/devops-maestro17/clusterHub.git
        targetRevision: main
        helm:
          valueFiles:
          - 'values-{{cluster}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true
