apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: guestbook
 namespace: argocd
spec:
 generators:
 - list:
     elements:
     - cluster: guestbook-dev
       url: https://DD0AD4BB46FB37E1CCE667B874DCF2BD.gr7.ap-south-1.eks.amazonaws.com
 template:
   metadata:
     name: '{{cluster}}-guestbook'
   spec:
     project: default
     source:
       repoURL: https://github.com/devops-maestro17/clusterHub.git
       targetRevision: HEAD
       path: guest-book/apps/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: {{cluster}}
     syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true	