apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://34.173.21.41
      - cluster: qa
        url: https://104.197.109.251
      - cluster: prod
        url: https://34.172.16.59
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        path: helm-charts
        repoURL: https://github.com/devops-maestro17/clusterHub.git
        targetRevision: main
        helm:
          valueFiles:
          - 'values-{{cluster}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true