apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: dev-cluster-url
      - cluster: qa
        url: qa-cluster-url
      - cluster: prod
        url: prod-cluster-url
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        path: helm-charts
        repoURL: https://github.com/devops-maestro17/multiKubeDeploy.git
        targetRevision: main
        helm:
          valueFiles:
          - 'values-{{cluster}}.yaml'
      destination:
        server: '{{url}}'
        namespace: '{{cluster}}'
      syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true
